import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/Navbar/NavBar";
import Providers from "@/providers/ThemeProvider";
import ToggleThemeProvider from "@/providers/ToggleThemeProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ToggleThemeProvider>
          <Providers>
            <NavBar />
            <main>{children}</main>
          </Providers>
        </ToggleThemeProvider>
      </body>
    </html>
  );
}
